name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"  # Use your preferred version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --base-href="/My_Portfolio/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
